# Generated by Django 3.0.5 on 2020-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/no-img.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
